server:
  port: 8000

spring:
  thymeleaf:
    cache: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/grapefarm?characterEncoding=utf8&serverTimezone=CTT
    username: root
    password: 5pzzZVwzhTh5
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 3000
      max-lifetime: 1800000
  mail:
    host: smtp.qq.com
    username: 825619590@qq.com
    password: emmrcvwlalchbbjg # qq 邮箱配置的密码，非邮箱登录密码，在邮箱开启 smtp 的设置处配置，需要绑定手机并发短信才能设置
    defaultEncoding: UTF-8
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
          ssl:
            trust: smtp.qq.com
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          starttls:
            enable: true
            required: true


mail:
  fromMail:
    addr: 825619590@qq.com

paypal:
  mode: sandbox
  client:
    app: ARui9JpREdR7Nu7fFYBmdgAh4RMMaBaa_NXQp4B6DjtqsfZCqG2aIj4spqAcNTjTjP8jaKxMt19XNakR
    secret: ENCubpYF2jVkj5mFemTdCgXBnI7NeOFyphgb6s2sPdAOWpGIinoqqHsD8ghKrm8R2g9QnjW5gCfF6INR