# 指定哪个配置文件生效
spring:
  profiles:
    active: prd
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


swagger:
  base-package: com.pw.grapefarm
  authorization:
    key-name: Authorization


